const webApiUrl = "http://localhost:5012/api";

export const serverUrls = {
    api: webApiUrl,
    auth: webApiUrl + "/user/auth",
    register: webApiUrl + "/user/register",
    user: webApiUrl + "/user",
    userAvatar: webApiUrl + "/user/avatar",
    changeAvatar: webApiUrl + "/user/change_avatar",
    lastListened: webApiUrl + "/tracks/last_listened",
    ping: webApiUrl + "/ping",
    trackToShow: webApiUrl + "/tracks/get_by_id_to_show",
    trackToListen: webApiUrl + "/tracks/get_by_id_to_listen",
    lastListenedPlaylists: webApiUrl + "/playlists/last_listened",
    lastListenedAlbums: webApiUrl + "/albums/last_listened",
    musicians: webApiUrl + "/musicians",
    musiciansSearch: webApiUrl + "/musicians/search",
    popularAlbums: webApiUrl + "/albums/popular",
    popularTracks: webApiUrl + "/tracks/popular",
    setLastListenedAlbum: webApiUrl + "/albums/set_last_listened",
    userUpdate: webApiUrl + "/user/update",
    changePassword: webApiUrl + "/user/change_password",
    userSubscription: webApiUrl + "/user/subscription",
    subscriptions: webApiUrl + "/subscriptions",
    purchaseSubscription: webApiUrl + "/subscriptions/buy",
    tracksPopularForAll: webApiUrl + "/tracks/popular_for_all",
    tracksSearch: webApiUrl + "/tracks/search",
    createPlaylist: webApiUrl + "/playlists/create",
    playlists: webApiUrl + "/playlists",
    setLastListenedPlaylist: webApiUrl + "/playlists/set_last_listened",
    playlistUpdate: webApiUrl + "/playlists/update",
    deletePlaylist: webApiUrl + "/playlists/delete",
    addTrackToPlaylist: webApiUrl + "/playlists/add_track",
};